# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App - TEST-REACTION-APP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Recommended for React apps (or keep ~22 if you're sure)

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build

      - name: Add web.config for React SPA support
        run: |
          echo ^<?xml version="1.0" encoding="utf-8"?^>^
          ^<configuration^>^
            ^<system.webServer^>^
              ^<rewrite^>^
                ^<rules^>^
                  ^<rule name="ReactRoutes" stopProcessing="true"^>^
                    ^<match url=".*" /^>^
                    ^<conditions logicalGrouping="MatchAll"^>^
                      ^<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" /^>^
                      ^<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" /^>^
                    ^</conditions^>^
                    ^<action type="Rewrite" url="/index.html" /^>^
                  ^</rule^>^
                ^</rules^>^
              ^</rewrite^>^
            ^</system.webServer^>^
          ^</configuration^> > build/web.config

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TEST-REACTION-APP'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_70F8DED0CBC2455C981B495E3920C13B }}
